// <auto-generated />
using AirportsAndFlights.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirportsAndFlights.Migrations
{
    [DbContext(typeof(AirportsAndFlightsContext))]
    [Migration("20230429083044_FlightsTableAdded")]
    partial class FlightsTableAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirportsAndFlights.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AirportCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirportName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NoPassengersAnnually")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Airport");
                });

            modelBuilder.Entity("AirportsAndFlights.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeDestinationAirport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeOriginAirport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartureTimeInMinutesSinceMidnight")
                        .HasColumnType("int");

                    b.Property<int>("FlightDurationInMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Flight");
                });
#pragma warning restore 612, 618
        }
    }
}
